---
title: 'Statistical Data Mining: Self Organizing Maps and PCA'
author: "Thankam Abish"
date: "April 10, 2020"
output:
  html_document:
    df_print: paged
---

```{r echo = T, results = 'hide', message=FALSE, warning=FALSE}
library(ElemStatLearn)
library(kohonen)
library("multtest")
library("fpc")
library("cluster")
library("bootcluster")
```

### NCI Data
#### Self Organizing Map of NCI Data

```{r}
data(nci)

# fit an SOM
set.seed(1234)
som_grid_nci <- somgrid(xdim = 14, ydim = 14, topo = "hexagonal")
som_nci <- som(nci, grid = som_grid_nci, rlen = 3000)

x11()
codes <- som_nci$codes
som_nci$codes <- codes[[1]][,c(1:10)]
plot(som_nci, main = "NCI Data")
x11()
som_nci$codes <- codes[[1]][,c(11:20)]
plot(som_nci, main = "NCI Data")
som_nci$codes <- codes

x11()
plot(som_nci, type = "changes", main = "NCI Data")

x11()
plot(som_nci, type = "count")

x11()
plot(som_nci, type = "mapping")

# component plane plots
codes<- som_nci$codes[[1]]
x11()
par(mfrow=c(4,5))
for (i in 51:64){
  #x11()
  plot(som_nci, type = "property", property=codes[,i], main = colnames(codes)[i])
}

coolBlueHotRed <- function(n, alpha = 1){rainbow(n, end=4/6, alpha = alpha)[n:1]}

x11()
plot(som_nci, type = "dist.neighbours", palette.name = coolBlueHotRed)

```

#### Creating clusters on self organizing map

```{r}
codes <- som_nci$codes[[1]]
d <- dist(codes)
hc <- hclust(d)

x11()
plot(hc)

som_cluster_nci <- cutree(hc, h = 25)

my_colors <- c("blue","green2","red", "yellow")
my_bhcol <- my_colors[som_cluster_nci]

x11()
plot(som_nci, col = "black", bgcol = my_bhcol)
add.cluster.boundaries(som_nci, som_cluster_nci)
```

### US Arrests Data
#### Self Organizing Map of US Arrests Data

```{r}
data(USArrests)
arrests <- scale(USArrests)
set.seed(12353)

distance <- dist(arrests, method = "euclidean")
hc <- hclust(distance, method = "complete")
x11()
plot(hc, hang = -1, labels = row.names(arrests))

rect.hclust(hc, k=3, border="red")
ct <- cutree(hc, h=150)

set.seed(1234)

arrests = data.matrix(arrests)
som_grid_US <- somgrid(xdim = 4, ydim = 4, topo = "hexagonal")
som_US <- som(arrests, grid = som_grid_US, rlen = 2500)

x11()
plot(som_US, main = "USArrests Data")

x11()
plot(som_US, type = "changes", main = "USArrests Data")

x11()
plot(som_US, type = "count")

x11()
plot(som_US, type = "mapping")

```

#### Clustering on self organizing map

```{r}
codes <- som_US$codes[[1]]
d <- dist(codes)
hc <- hclust(d)

x11()
plot(hc)

som_cluster_US <- cutree(hc, h = 3)

# plot the SOM with the found clusters

my_pal <- c("red", "blue", "yellow")
my_bhcol <- my_pal[som_cluster_US]

x11()
plot(som_US, type = "mapping", col = "black", bgcol = my_bhcol)
add.cluster.boundaries(som_US, som_cluster_US)

```

### Swiss Bank Notes Data
#### PCA with only real notes

```{r}
load("SwissBankNotes.RData")
SBN <- SwissBankNotes
pc_real <- prcomp(SBN[1:100,], center = TRUE, scale = TRUE)
pc_fake <- prcomp(SBN[101:200,], center = TRUE, scale = TRUE)
pc_both <- prcomp(SBN, center = TRUE, scale = TRUE)
x11()
biplot(pc_real)
```

#### PCA with only fake notes

```{r}
x11()
biplot(pc_fake)
```

#### PCA with all notes

```{r}
x11()
plot(x = pc_both$x[1:100,1],y = pc_both$x[1:100,2], 
     col = "blue", xlab = "PC 1", ylab = "PC 2", 
     main = "Real vs Counterfeit Swiss Bank Notes",
     xlim = range(-4:4), ylim = range(-4:4))
points(x = pc_both$x[101:200,1],y = pc_both$x[101:200,2], col = "red")
legend("bottomright", c("Real","Fake"),
       fill=c("blue","red"))
x11()
biplot(pc_both)
```

